### ISSUE TITLE
Plotting of predictions on tracks for multiclassifier

### ISSUE THREAD

**Issue by mkabra** [kristinbranson/JAABA#291]
Currently, not sure what is plotted when "Automatic" option is selected for plotting the tracks. For multiclassifier, instead of a single automatic option, maybe we should have an option for each behavior. Even for manual option it would be better to plot a single behavior.

**Comment by allenleetc** [comment]
Spec: there is now a "behaviorFocus" pulldown for multiclassifier projects that lets you specify either "unfocused" or focus on a single behavior. When unfocused, labels are shown for **all** classifiers, in both manual and automatic mode. This is sort of useful if labels are sparse, but when labels overlap then things get obscured. However, when behaviorFocus is on a single classifier, then only labels relevant to that classifier are shown.
