### ISSUE TITLE
Automatic Timeline Behavior is unclear for multiclassifier

### ISSUE THREAD

**Issue by mkabra** [kristinbranson/JAABA#292]
The drop down menu to select what is shown on the automatic prediction timeline doesn't work. Also, it is not clear what if plotted when the scores are imported as well as computed. For multiclassifier, instead of showing multiple plots like prediction, scores and imported scores, maybe show only one type of plot for all the behaviors (like prediction, scores, imported etc)?

**Comment by allenleetc** [comment]
Thought about this a little, am thinking about two usages:
1. (What you describe) One quantity shown over all behaviors/classifiers
2. The current 3-part timeline (or more generally, some set of multiple quantities), shown for a single user-selected behavior/classifier. 

Seems like both could be useful, what do you think? Is it worth doing both of these? For 2, I would add a UI element to allow specification or "focus" on a single classifier. The ability to focus on a single classifier could be useful in other contexts, eg perhaps issue #291. Or, there was the suggestion to reduce the number of labeling buttons by adding a pulldown for specifying the "current" behavior/classifier that is being labeled.

**Comment by mkabra** [comment]
Yeah, I like the two usage and the focus idea. Should be useful. As for label buttons, I'm not sure because I anyway use keyboard shortcuts. Reducing the number of button maybe useful so that it is less cluttered.
