### ISSUE TITLE
Shift + arrow keys behavior is not well defined

### ISSUE THREAD

**Issue by mkabra** [kristinbranson/JAABA#294]
Shift + arrow key shortcut doesn't work for multiclassifier.

**Comment by allenleetc** [comment]
Ctrl + arrows don't seem to work either

**Comment by allenleetc** [comment]
## Spec
* Ctrl-left, Ctrl-right
** When behaviorFocus is off, jump to next/prev bout with any label
** When behaviorFocus is on, jump to next/prev bout for classifier in focus (either beh or no-beh)
