### ISSUE TITLE
Edit > Compression Prefs settings not applied

### ISSUE THREAD

**Issue by allenleetc** [kristinbranson/JAABA#305]
The settings specified under Edit > Compression prefs do not appear applied. In CompressionPreferences.m, the various video settings chosen are set on the JLabel figure guidata, rather than the guidata's .guidata property, ie the JLabelGUIData object. When these settings are to be used in eg make_jlabel_results_movie, props appear to be read off the JLabelGUIData object.

In general looks like there is some crufty code in this area, eg make_jlabel_results_movie references handles.guidata.avifileTempDataFile but JLabelGUIData does not contain a prop with this name.

**Comment by allenleetc** [comment]
Making movie clips also doesn't seem to work with multiple monitors. I am sure I am in the weeds but hey.

**Comment by mkabra** [comment]
Don't think that code has been touched in a long time. That's why the
guidata mismatch. Hope you won't get scared in these dank and musty caves.

Mayank

**Comment by arobie** [comment]
At some point changing the compression prefs like frame rate did change the clips (created by left clicking in the timeline). I haven't done that in a long time so I'm not sure when the functionality was lost.
