### ISSUE TITLE
auto timeline context menu "Accept [Predicted Chase bout xxxx:yyyy]" has no effect

### ISSUE THREAD

**Issue by allenleetc** [kristinbranson/JAABA#306]
Looks like this menu item doesn't do anything, JLabel:contextmenu_timeline_automatic_accept_bout_Callback is empty

**Comment by mkabra** [comment]
This was supposed to add the predictions to the labels. Accept meant that
the user accepts the predictions. I don't think we ever used or missed this
functionality. You can remove this menu item.

Mayank

**Comment by allenleetc** [comment]
OK, yeah I figured it couldn't have been missed much :O
