### ISSUE TITLE
Visualize Classifier Error

### ISSUE THREAD

**Issue by arobie** [kristinbranson/JAABA#314]
When we try to visualize the classifier, we get this error (using 2015a Matlab on Windows):

Error using colorbar (line 55)
Attempt to reference field of non-structure array.

Error in ShowWindowFeatureWeights (line 104)
hcolorbar = colorbar('peer',hax(2),'Location','South');

Error in JLabel>menu_classifier_visualize_Callback (line 6773)
[hweight,hscore,hax,hfig,hylabel,hticks,hcolorbar,...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in JLabel (line 37)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)JLabel('menu_classifier_visualize_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating Menu Callback

~Alice and Maansi

**Comment by mkabra** [comment]
Fixed this. It was because of the changes in the graphics framework.
