### ISSUE TITLE
store GT suggestions in jab file?

### ISSUE THREAD

**Issue by arobie** [kristinbranson/JAABA#316]
Is there an important reason to have GT suggestions be an external file? I find people (myself included) forgot to export them more often then not, and then either have to restart groundtruthing or if they're finished can't use the navigation functions without the suggestions. Storing the most recent suggestions in the jab file seems straight forward to me. An alternative might be a flag for GT suggestions so that if someone tries to close without exporting them, a reminder pops up.

**Comment by mkabra** [comment]
Implemented this.
