### ISSUE TITLE
Unable to add more videos in Ground-Truthing Mode

### ISSUE THREAD

**Issue by cachitas** [kristinbranson/JAABA#320]
I am using the current master version (ffd8de5d5fe702b7cd0377805a1fba610fdfb5cd) and MATLAB 2015a.

I opened my experiment in Ground-Truthing mode, added a video and did a random annotation.

When I reopen the .jab in Ground-Truthing mode to add more videos, it gives this error:

```
Index exceeds matrix dimensions.

Error in JLabelData/GetGTSuggestionIdx (line 9186)
          start = obj.randomGTSuggestions{expi}(flies).start;

Error in JLabel>UpdateTimelineImages (line 1801)
    [suggest_t0s,suggest_t1s] =
    get_interval_ends(jldata.GetGTSuggestionIdx(jldata.expi,jldata.flies));
    
Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in JLabel (line 37)
    gui_mainfcn(gui_State, varargin{:});

Error in JLabelGUIData/jlabelCall (line 1082)
      JLabel(fcn,handles,varargin{:});

Error in JLabelGUIData/labelsPlotInit (line 1048)
      self.jlabelCall('UpdateTimelineImages'); % sets other
      state on self.labels_plot

Error in JLabel>SetCurrentFlies (line 1665)
handles.guidata.labelsPlotInit();

Error in JLabel>SetCurrentMovie (line 1520)
handles = SetCurrentFlies(handles,flies,true,false);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in JLabel (line 37)
    gui_mainfcn(gui_State, varargin{:});

Error in JModifyFiles>pushbutton_done_Callback (line 335)
    JLabel('SetCurrentMovie',guidata(figureJLabel),v);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in JModifyFiles (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)JModifyFiles('pushbutton_done_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating UIControl Callback
```

and selecting the video does nothing.

**Comment by mkabra** [comment]
Hey Hugo,

I've pushed a fix. Can you try now and see if it works?

**Comment by cachitas** [comment]
Yes, I am now able to add more videos. But every time I ask for a random interval to annotate, the interval comes from the first video until it no longer allows me to pool anymore... Could this be related?

**Comment by mkabra** [comment]
Hi Hugo,

Every time you add a new video you need to ask for new set of random
interval to ground truth. Unfortunately, what this means is that the
intervals for earlier movies will get modified. However, if you had labeled
them then you don't need to relabel the same fly again because the earlier
labels will be used when computing the ground truth performance.

Mayank

**Comment by cachitas** [comment]
But my problem is that only the first video provides frames to label, independently of the number of videos in the experiment list. Maybe I am not doing this right... What is the procedure if I want to Ground-Truth a handful of videos?

Also, if the intervals for earlier movies get modified, how can the existing labels be reused?

**Comment by mkabra** [comment]
Hi Hugo,

After you done adding a new movie, you again need to do Menu-> View ->
Suggest Ground Truthing Intervals -> Random. I just tested this and it is
working fine. You can also check if intervals have been suggested or not by
looking at the Go -> Switch Target window.

And ground truthing is computed based on frames that have been labeled and
not based on what has been suggested. The intervals are just suggestions.

Mayank

**Comment by cachitas** [comment]
I think I am getting there... I was really confused on how this works.
Let's us close this issue then. Any further problems I may face, I'll take them to the discussion group.
Thank you for your help!
