### ISSUE TITLE
JAABA\misc\savefig.m function interferes with matlab native saving functionality

### ISSUE THREAD

**Issue by stephenhuston** [kristinbranson/JAABA#323]
Hi,

JAABA\misc\savefig.m has the same function name as the native Matlab function used for normal figure saving: http://www.mathworks.com/help/matlab/ref/savefig.html.  On my machine this crashes normal non-JAABA figure saving.  Figure window->file menu->save as->temp.fig gives the error "Error using fileparts (line 43) input must be a row vector of characters)".

I understand this could be avoided by carefully setting up paths and function precedence order etc., but it would make life easier if the two functions had different names.

Thanks

**Comment by arobie** [comment]
I think this is my fault. I couldn't open a jab file created on windows on a linux machine and we changed the fileparts code as a fix. (It should be noted Kristin thought this was a bad fix at the time.) But I'm not sure what a better way to fix it. It would be nice if the fixed maintained the ability to open jab files across platforms.

**Comment by kristinbranson** [comment]
I don't think this is the issue with fileparts, though I am still against this :). 

I just committed a change to JAABA renaming savefig to savefig1. There was no savefig in older versions of MATLAB.

**Comment by kristinbranson** [comment]
I just committed a change to JAABA renaming savefig to savefig1. There is
no savefig in older versions of MATLAB. If you call JAABA's savefig, you
may need to change your code.

**Comment by allenleetc** [comment]
+1, I have had <JCtrax>/misc/savefig.m renamed to savefig_JCtrax.m for ages. Was always worried about breaking something. I can make the same change in JCtrax next time I'm in there if necessary.
