### ISSUE TITLE
misc/strsplit overload of builtin breaks MATLAB profiler on 16b

### ISSUE THREAD

**Issue by allenleetc** [kristinbranson/JAABA#324]
misc/strsplit.m has a different API than the builtin function with the same name (eg the builtin accepts optional PV pairs). On 16b this is breaking the profiler when I have JAABA on the path; there may be other unintended consequences too.

**Comment by adamltaylor** [comment]
Also, the JAABA strsplit() gives different output from the builtin strsplit() for inputs such as

strsplit('1.21, 1.985, 1.955, 2.015, 1.885', ', ') 

It seems like the JAABA version is only using the first character of the delimiter string (the 2nd arg)?

This created issues on a Hantman Lab rig machine that had both WaveSurfer and JAABA on the Matlab path at the same time, b/c WaveSurfer uses strsplit() in places.

**Comment by mkabra** [comment]
strsplit also broke matlab's tab completion, so yeah it was kind of annoying. I checked the code and there doesn't seem to be a strong reason for its existence. So, I've renamed it to strsplit_jaaba . I tested JAABA quickly and doesn't seem to matter.
