### ISSUE TITLE
Error when opening movie

### ISSUE THREAD

**Issue by xneven** [kristinbranson/JAABA#335]
Hello, I'm trying out JAABA for the first time. I've specified the experiment directory containing my video and trx.mat file, however, after the missing perframe files are successfully generated and matlab tries to open the video i get the following error:

![image](https://user-images.githubusercontent.com/66742593/88422018-73103880-cde1-11ea-9245-0925b02634ca.png)

A bit of the error message is missing at the top because this freezes matlab and I can't scroll up, I have to kill the process to try again.

I've tried using .mov and .avi formats, which doesn't make a difference.
I generated my own trx.mat files because I am using tracking data from the new multianimal DeepLabCut, for which the createfromDeepLabCut function in APT has not been updated, so perhaps errors in my trx.mat might be responsible?

**Comment by mkabra** [comment]
Part of the error message is clipped. Can you send that? Most likely the
problem is due to missing codecs on the machine. Can you open the movie
using Matlab's VideoReader function (
https://www.mathworks.com/help/matlab/ref/videoreader.html) which is the
underlying function that JAABA uses to open the video in most cases?

Mayank

**Comment by mkabra** [comment]
Oh you did mention why the error message is clipped. Never mind about that.
Try out the VideoReader function and maybe send a sample video.

**Comment by xneven** [comment]
Thanks that seemed to be the issue because Ubuntu no longer uses gstreamer0.10-ffmpeg. Solved it by renaming libstdc++.so.6 in rootMATLABfolder/.../sys/os/glnxa64/ to something else like libstdc++.so.6.old so that MATLAB is forced to use Linux defaults :)
