### ISSUE TITLE
Number of labeled frames

### ISSUE THREAD

**Issue by GabrielStahl** [kristinbranson/JAABA#336]
How can I see on how many frames the current classifier is trained on?

**Comment by mkabra** [comment]
Currently, there is no direct way to get this statistic. You can however
use the Go -> Switch Targets to find (and copy) the number of labels for
each individual animal and use that to find the total number of labels. Or,
you can do cross-validation where in the end the results window will show
the number of labels.

Mayank

**Comment by GabrielStahl** [comment]
Thank you very much for the fast and helpful response!

Kind regards,
Gabriel
