### ISSUE TITLE
Precise format of trx.mat parameters

### ISSUE THREAD

**Issue by catubc** [kristinbranson/JAABA#338]
Hello
I'm a postdoc at NYU and we're trying to use SLEAP (https://github.com/murthylab/sleap) to track animals and potentially JAABA to do the behavior clustering.

Using python (scipy.savemat function) we managed to format some of our SLEAP output (after some postprocessing) into a trx.mat file that is correctly read by JAABA. but it seems some of the datatypes are not correct as JAABA crashes at the plotting stage (see attached error logs).

![trx_format](https://user-images.githubusercontent.com/4267452/107516812-3b19e880-6bad-11eb-8c76-b622dcb43f41.png)
![jaaba_crash](https://user-images.githubusercontent.com/4267452/107516813-3c4b1580-6bad-11eb-9aef-075514613b3a.png)

Can you provide us with the precise description including datatypes of the trx.mat file so we can try writing a python script for this import step? The description here is a good start, but it does not have data types and also has a few more parameters not described in the setup instructions:

http://jaaba.sourceforge.net/DataFormatting.html

Any other advice is much appreciated.

Thank you so much,
catubc

**Comment by mkabra** [comment]
Hi,

Do you only have a single animal? Because the trx stuct array has only one
element. And looking at the trx struct, all your fields are int32 while
they should be float. Particularly, dt and a_mm, b_mm don't make much sense
as int32. Converting all the fields to float is likely to get rid of the
errors. If they don't can you send an example trx file?

Mayank

**Comment by catubc** [comment]
Hi Mayank
Thanks for this. I did manage to get a python script now to generate a trx.mat file that JAABA will load. I will post the python code shortly for others looking to convert data from numpy arrays directly to .mat using python only.
I'll leave the issue open until I have a chance to upload the code.
Thanks again,
catubc

**Comment by catubc** [comment]
Ok, I have a working solution now. It uses the get_scores_from_slp python notebook file here to convert the .slp files to angles, locations etc.

https://github.com/catubc/gerbil_project/tree/main/sleap_tools

and this matlab function to rewrap the tracks for my 4 animals using matlab functions (I couldn't figure out a python only solution). 

function p = process_trx(file)
    load(file)
    trx = [trx.a, trx.b, trx.c, trx.d]
    [dir,pathparts] = fileparts(file)
    file2=strcat(dir,'/jaaba/trx2.mat')
    save(file2, 'trx')

Thanks so much,
catubc

**Comment by CharlotteRosher** [comment]
Hi Catubc,

Thanks for sharing your solution!
I am trying to do something similar, but this link is broken. Please could you share another link?

Thanks,
Charlie
