### ISSUE TITLE
Multi-animal classification - how to identify which target animal is generating the label 

### ISSUE THREAD

**Issue by catubc** [kristinbranson/JAABA#343]
Hello

We have a multi-animal (gerbil) paradigm in which we are trying to label social behaviors.  We are finding the jaaba classifiers are starting to work, but are wondering whether the .mat file (or the .jab file?) contain more than just single animal class information?  In particular, we'd like to further disambiguate by identifying specifically which 2 animals are generating the label.

I attach an example where a male (blue dots) is approaching a huddle containing a female (red) and pup (green).  Is it possible to know which of these 2 huddled animals is also responsible for the "approach" label?  (This example is not ideal, but we have similar cases where the animals being approached are separated by substantial distance).

Thanks so much!

![jaaba_gerbils](https://user-images.githubusercontent.com/4267452/128316038-6d5251cf-da73-4cb2-8aa0-b628e970e689.png)

**Comment by arobie** [comment]
If you know which social perframe features your approach behavior uses you
can probably approximately figure it out (check out visualize classifier).
The social perframe features are computed with different metrics of which
is the 'closest' animal.
Alternatively, you can define a behavior of 'being approached' that is
based on the current animal and that might give the information you want
more directly. But at this time we don't have multianimal behaviors.
Cheers
Alice

**Comment by catubc** [comment]
Thanks Alice. This is very helpful.  I think we could probably figure out this from body centers.
We might also train additional classifiers to deal with this.
