### ISSUE TITLE
Reference to non-existent field 'labels' when importing .lbl file from APT

### ISSUE THREAD

**Issue by harshk95** [kristinbranson/JAABA#345]
Hi,
I have a DLC project that we imported into APT and want to run JAABA on. When I import the .lbl file into JAABA using 'Import from APT project'

Reference to non-existent field 'labels'.
Error in APTProject>initialize (line 246)
s = apt.labels{ndx};
Error in APTProject>APTProject_OpeningFcn (line 171)
handles = initialize(handles);
Error in gui_mainfcn (line 220)
feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
varargin{:});
Error in APTProject (line 40)
[varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
Error in ProjectSetup>uibuttongroup1_SelectionChangedFcn (line 1070)
aptStruct = APTProject('lbl_file',lbl_file);
Error in gui_mainfcn (line 95)
feval(varargin{:});
Error in ProjectSetup (line 42)
gui_mainfcn(gui_State, varargin{:});
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ProjectSetup('uibuttongroup1_SelectionChangedFcn',get(hObject,'SelectedObject'),eventdata,guidata(get(hObject,'SelectedObject')))
Error using uiwait (line 81)
Error while evaluating ButtonGroup SelectionChangedFcn.

Would appreciate any help
Thanks!

**Comment by mkabra** [comment]
Hi,

I've pushed a fix. Can you pull the latest version from the git repo and
try again?

Mayank

**Comment by harshk95** [comment]
Thanks it works now!

**Comment by luneo-1** [comment]
I also want to use JAABA to label and classification mice behaviour. Now, I only have a Deeplabcut results,  I want to know how about JAABA

**Comment by mkabra** [comment]
Currently, there is no way to import Deeplabcut results into JAABA. You
could try to import Deeplabcut labels into APT and train a new tracker and
then import the APT trk result files into JAABA.

Mayank
